# Dark Theme Colors
# Got Theme from 'alacritty-themes' Node Package

# theme = "vscode.dark"

[colors]
# author = "senpai-10"
# name = "vscode (dark)"

[colors.bright]
black = "#666666"
blue = "#3b8eea"
cyan = "#29b8db"
green = "#23d18b"
magenta = "#d670d6"
red = "#f14c4c"
white = "#e5e5e5"
yellow = "#f5f543"

[colors.cursor]
cursor = "#cccccc"
text = "#1d1f21"

[colors.normal]
black = "#000000"
blue = "#2472c8"
cyan = "#11a8cd"
green = "#0dbc79"
magenta = "#bc3fbc"
red = "#cd3131"
white = "#e5e5e5"
yellow = "#e5e510"

[colors.primary]
background = "#1E1E1E"
foreground = "#D4D4D4"

[window]
# Decorations theme variant (Linux/BSD only)
# Override the variant of the GTK theme/Wayland client side decorations.
decorations_theme_variant = "Dark"
